Repository UltimateShVU/python-nt-analyser, pull requests merged in 2023-03, with the labels that each got.

#2 fix-1: small refactoring and internal signal handling added
  analyze.py
  analyze_defs.py
  helpers.py
  main.py
Labels: code review

#3 Исправлена ошибка в проверке типа SSH соединения
  analyze.py
Labels: bug, code review

#6 fix: #2 refactoring
  analyze.py
  analyze_defs.py
  complex.py
  main.py
Labels: code review, Жёстко наревьювал
